<?php
if (
    !\Agrodefesa\Controller\Authentication\Login::checkUsuarioLogado()
    && $this->layout()->nomeAction == 'login'
) {
    return;
}
?>
<div id="agr-cabecalho" class="noprint">
    <div class="mdl-layout mdl-layout--fixed-header">
        <header style="margin: 0;" class="mdl-layout__header is-casting-shadow">
            <div style="padding: 0;" class="mdl-layout__header-row">
                <?php
                $cabecalho = new \Agrodefesa\View\Componentes\Toolbar\Toolbar();
                $cabecalho->setRoute($this->layout()->nomeAction, $this->nomeController, $this->nomeModule, $this->nomeModuleUrl);
                print $cabecalho->render();
                // print_r($this->layout());
                ?>
                <?php if (!IS_PRODUCAO && !\Agrodefesa\Util\Util::isMobile()) { ?>
                    <?php if (!in_array(GIT_BRANCH, ["master", "qa"])) { ?>
                        <ul>
                            <li>TESTE FUNCIONAL</li>
                            <li><strong>Responsável:</strong> <?= RESPONSAVEL_TESTE_FUNCIONAL ?></li>
                            <li><strong>Branch:</strong> <?= GIT_BRANCH ?></h4></li>
                        </ul>
                    
                    <?php } ?>
                <?php } ?>
            </div>
        </header>
    </div>
</div>
<script>    
    // quando usuario solicitar aprovação de um comprovante
    if (constantes.isProducao) {
        const socket = io("wss://sigaderr.aderr.com.br:3332", {rejectUnauthorized: false});
        socket.on("fundepec", function(data) {
            if ( <?= \Db\Acesso\Usuario::UsuarioEGrupoFundepec(); ?>) {
                Toastify({
                    text: `${data.msg}`,
                    duration: 360000,
                    destination: `${data.link}`,
                    newWindow: true,
                    close: true,
                    gravity: "top", // `top` or `bottom`
                    position: "right", // `left`, `center` or `right`
                    stopOnFocus: true, // Prevents dismissing of toast on hover
                    style: { background: "linear-gradient(to right, #282A36, #282A36)", },
                    onClick: function(){} // Callback after click
                }).showToast();
                notificacaoAudio();
            }
        });

        socket.on("geral", function(client,data) {
            if (client == <?= \Db\Acesso\Usuario::getUsuarioLogado()->id_pessoa; ?>) {
                Toastify({
                    text: `${data.msg}`,
                    duration: 360000,
                    destination: `${data.link}`,
                    newWindow: true,
                    close: true,
                    gravity: "top", // `top` or `bottom`
                    position: "right", // `left`, `center` or `right`
                    stopOnFocus: true, // Prevents dismissing of toast on hover
                    style: { background: "linear-gradient(to right, #282A36, #282A36)", },
                    onClick: function(){} // Callback after click
                }).showToast();
                notificacaoAudio();
            }
        });
    }

    function avisarFundepec(data) {
        if (constantes.isProducao) {
            data.msg = "Cobrança FUNDEPEC aguardando aprovação";
            socket.emit('fundepec', data);
        }
    }
    
    function avisarUsuario(idPessoa, data) {
        if (constantes.isProducao) {
            socket.emit('geral', {
                idPessoa: idPessoa, 
                data
            });
        }
    }


    function notificacaoAudio() {
        const music = new Audio('audio/notification.wav');
        music.play();
    }
</script>
